FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json for efficient caching
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the application in development mode
CMD ["npm", "run", "dev"]